### PR TITLE
fix: pre-calculate cluster node positions and reduce drag disturbance

### LINKED ISSUE #3: Improve cluster topology graph positioning and drag behavior
Problem

Nodes overlap on initial render, then slowly animate apart
Dragging nodes feels jerky/unnatural

Expected

Nodes should start in non-overlapping positions (e.g., masters in a circle, replicas offset)
Dragging should be smooth with links following immediately

Fix Ideas

Pre-calculate initial x/y positions based on role before simulation runs
Increase alphaDecay for faster settling
Review drag handlers (fx/fy usage)

### PR DESCRIPTION
**Pull request by Shanb007**
## Summary                                                                                                                                                                                                                             
   
  Fixes #3                                                                                                                                                                                                                             
                                                                                                                                                                                                                                       
  Cluster topology graph nodes rendered tightly clustered on initial load and slowly animated apart. Additionally, clicking/dragging any single node caused all other nodes to reposition.

  ## Changes

  **Pre-calculate initial node positions based on role**
  - Master nodes are placed in a circle around the center of the canvas
  - Replica nodes are placed offset outward from their respective master
  - Saved positions (from previous drag) are still respected
  - This eliminates the tight clump -> slow spread animation on first render

  **Increase `alphaDecay` (0.0228 -> 0.05)**
  - The simulation now settles ~2x faster since nodes already start in good positions
  - Only minor adjustments needed, no reason for a long animation

  **Lower drag `alphaTarget` (0.3 -> 0.01)**
  - Previously, clicking any node reheated the entire force simulation to 0.3, causing all nodes to reposition
  - Now it only warms enough for links to follow the dragged node without disturbing neighbors

<!-- CURSOR_SUMMARY -->
---

> [!NOTE]
> **Low Risk**
> UI-only layout and physics-parameter tweaks confined to `ClusterTopologyGraph.tsx`, with no auth/data-path changes; main risk is minor visual regressions for unusual cluster shapes or resizing.
> 
> **Overview**
> Improves the cluster topology graph’s initial layout by *precomputing node positions* (masters arranged in a circle; replicas placed offset from their master) while still honoring previously dragged/saved positions, eliminating the initial “clump then spread” animation.
> 
> Tweaks D3 force simulation behavior to reduce disruption and settle faster: simulation only “reheats” for nodes without saved positions, increases `alphaDecay` to converge quicker, and lowers drag `alphaTarget` so dragging a node doesn’t cause the whole graph to reshuffle.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit ca92df1e174aaec80a772a56af5fba4239eae33d. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>
<!-- /CURSOR_SUMMARY -->

### CODE REVIEW

File: apps/web/src/components/cluster/ClusterTopologyGraph.tsx [hunk 1]
```diff
@@ -85,8 +85,52 @@ export function ClusterTopologyGraph({ nodes, nodeStats, viewToggle }: ClusterTo
...
     }
 
+    const width = containerWidth;
+    const height = CONTAINER_HEIGHT;
+    const centerX = width / 2;
+    const centerY = height / 2;
+
+    // Separate masters and replicas for circular layout
+    const masters = nodes.filter((n) => n.flags.includes('master'));
+    const replicas = nodes.filter((n) => !n.flags.includes('master'));
```
Comment (KIvanow) [inline apps/web/src/components/cluster/ClusterTopologyGraph.tsx]: Not blocking, but you can do the same with one pass

const masters = []
const replicas = []
nodes.forEach(el => either push to masters or replicas)

File: apps/web/src/components/cluster/ClusterTopologyGraph.tsx [hunk 2]
```diff
@@ -85,8 +85,52 @@ export function ClusterTopologyGraph({ nodes, nodeStats, viewToggle }: ClusterTo
...
+    const masterRadius = Math.min(width, height) * 0.2;
+    const replicaOffset = LINK_DISTANCE * 0.5;
+
+    function getInitialPosition(node: ClusterNode): { x: number; y: number } {
+      const saved = nodePositionsRef.current.get(node.id);
+      if (saved) return saved;
+
+      if (node.flags.includes('master')) {
+        const idx = masterIndexMap.get(node.id) ?? 0;
+        const angle = (2 * Math.PI * idx) / Math.max(masters.length, 1) - Math.PI / 2;
```
Comment (KIvanow) [inline apps/web/src/components/cluster/ClusterTopologyGraph.tsx]: This is the same as line 120. It would've been easier if the calculation is abstracted for easier refactoring

File: apps/web/src/components/cluster/ClusterTopologyGraph.tsx [hunk 3]
```diff
@@ -85,8 +85,52 @@ export function ClusterTopologyGraph({ nodes, nodeStats, viewToggle }: ClusterTo
...
+    const replicas = nodes.filter((n) => !n.flags.includes('master'));
+
+    // Map masterId -> index for circular placement
+    const masterIndexMap = new Map<string, number>();
+    masters.forEach((m, i) => masterIndexMap.set(m.id, i));
+
+    const masterRadius = Math.min(width, height) * 0.2;
+    const replicaOffset = LINK_DISTANCE * 0.5;
+
+    function getInitialPosition(node: ClusterNode): { x: number; y: number } {
```
Comment (KIvanow) [inline apps/web/src/components/cluster/ClusterTopologyGraph.tsx]: Please follow the repo style of arrow functions --> const getInitialPostion = (

**Review by KIvanow — CHANGES_REQUESTED** [review]
Thank you for the help! It is much appreciated! I've left a few comments. Only [this one](https://github.com/BetterDB-inc/monitor/pull/23/changes#r2807664107) is an actual request. The rest are nice to haves in terms of coding patterns.

File: apps/web/src/components/cluster/ClusterTopologyGraph.tsx [hunk 4]
```diff
@@ -85,8 +85,72 @@ export function ClusterTopologyGraph({ nodes, nodeStats, viewToggle }: ClusterTo
...
+      const masterAngle = getMasterAngle(masterId ? masterIndexMap.get(masterId) ?? 0 : 0);
+      const siblingsOfMaster = replicasByMaster.get(masterId ?? '') ?? [];
+      const replicaIdx = siblingsOfMaster.indexOf(node);
+      const spread = (replicaIdx + 1) * 0.4;
+      const replicaAngle = masterAngle + spread;
+
+      return {
+        x: centerX + (masterRadius + replicaOffset) * Math.cos(replicaAngle),
+        y: centerY + (masterRadius + replicaOffset) * Math.sin(replicaAngle),
+      };
```
[the remark this answers is not in the document]
Comment (Shanb007) [reply apps/web/src/components/cluster/ClusterTopologyGraph.tsx:149]: All references are the same object instances, `replicas` are built by pushing from `nodes`, `replicasByMaster` is built from `replicas`, and `getInitialPosition` is called from `nodes.map()`. No copies are made, so `indexOf` always finds a match for replica nodes.

File: apps/web/src/components/cluster/ClusterTopologyGraph.tsx [hunk 5]
```diff
@@ -85,8 +85,72 @@ export function ClusterTopologyGraph({ nodes, nodeStats, viewToggle }: ClusterTo
...
+      if (node.flags.includes('master')) {
+        const angle = getMasterAngle(masterIndexMap.get(node.id) ?? 0);
+        return {
+          x: centerX + masterRadius * Math.cos(angle),
+          y: centerY + masterRadius * Math.sin(angle),
+        };
+      }
+
+      // Replica: offset outward from its master
+      const masterId = node.master && node.master !== '-' ? node.master : '';
```
[the remark this answers is not in the document]
Comment (Shanb007) [reply apps/web/src/components/cluster/ClusterTopologyGraph.tsx:139]: Lines 114/139 intentionally return '' (map key for position grouping) while line 158 returns `undefined` (typed field for link building). 
Different fallbacks for different purposes - a shared helper wouldn't simplify this.

**Review by KIvanow — APPROVED** [review]
Two things needed before we can merge:

1. **CLA** — We just set up a CLA for outside contributions. Our bot should have commented on this PR asking you to sign. It's a standard Apache-based individual CLA, nothing unusual.

2. **Signed commits** — Our branch protection requires verified commit signatures. You'll need to sign your commits with a GPG or SSH key. GitHub has a guide here: https://docs.github.com/en/authentication/managing-commit-signature-verification

Once both are done we'll merge. Appreciate the contribution!
